Using Batch Script To Submit Jobs To AWS Batch

diff --git a/.github/workflows/BatchTest.yml b/.github/workflows/BatchTest.yml
--- a/.github/workflows/BatchTest.yml
+++ b/.github/workflows/BatchTest.yml
@@ -64,6 +64,36 @@ jobs:
           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
           echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
 
+      - name: Configure AWS Credentials For Batch
+        uses: aws-actions/configure-aws-credentials@main 
+        with:
+          role-to-assume: ${{ secrets.BATCH_ACCESS_ROLE_ARN }}
+          aws-region: eu-west-1
+          role-duration-seconds: 14400
+
+      - name: Submit Batch Job
+        id: submit_batch_job
+        run: |
+          chmod +x SikrakenDevOps/Batch/run_batch.sh 
+          JOB_ID=$(SikrakenDevOps/Batch/run_batch.sh "${{ vars.JOB_QUEUE }}" "${{ vars.JOB_DEFINITION }}" "${{ vars.TASK_COUNT }}" "${{ vars.CATEGORY }}" "${{ vars.BUDGET }}" "${{ vars.MODE }}")
+          echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT
+          
+      - name: Wait For Job Completion
+        run: |
+          JOB_ID="${{ steps.submit_batch_job.outputs.job_id }}"
+          while true; do
+            STATUS=$(aws batch describe-jobs --jobs "$JOB_ID" | jq -r '.jobs[0].status')
+            echo "Current status: $STATUS"
+            if [[ "$STATUS" == "SUCCEEDED" ]]; then
+              echo "Job completed successfully!"
+              break
+            elif [[ "$STATUS" == "FAILED" ]]; then
+              echo "Job failed!"
+              exit 1
+            fi
+            sleep 60
+          done
+          
   InvokeLambda:
       environment: Batch
       needs: [CheckoutRepositories]
